<a href="https://colab.research.google.com/github/sonam2006-sandanshiv/microsoft-workshop/blob/main/12_08_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
##dimesionality
import numpy as np
a1 = np.array([1,2,3,4])
a1.ndim

1

In [ ]:
a1.shape

(4,)

In [ ]:
a1 = np.array([[[[1,2,3,4]]]])
a1.ndim

4

In [ ]:
a1.shape

(1, 1, 1, 4)

In [ ]:
np.ravel(a1)

array([1, 2, 3, 4])

In [ ]:
a1.flatten()

array([1, 2, 3, 4])

In [ ]:
#stacking and spliting

In [ ]:
a1 = np.array([1,2,3,4])
a2=np.array([11,22,33,45])


In [ ]:
np.hstack([a1,a2])

array([ 1,  2,  3,  4, 11, 22, 33, 45])

In [ ]:
np.vstack([a1,a2])


array([[ 1,  2,  3,  4],
       [11, 22, 33, 45]])

In [ ]:
a3=np.arange(24)
np.split(a3,4)

[array([0, 1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17]),
 array([18, 19, 20, 21, 22, 23])]

In [ ]:
a1=np.arange(12).reshape(4,3)
a1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a1[:3,:2] #rows and col

array([[0, 1],
       [3, 4],
       [6, 7]])

In [ ]:
a1[1:-1,:2]

array([[3, 4],
       [6, 7]])

In [ ]:
a2=np.arange(36).reshape(6,6)
a2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [ ]:
a2[2:-3,2:-3]

array([[14]])

In [ ]:
a2[1::3] #for 2 rows 3 #skipping with reversing we will wirte in - y

array([[ 6,  7,  8,  9, 10, 11],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
a2[-2:1:-2,-2:0:-3]

array([[28, 25],
       [16, 13]])

In [ ]:
a2[::-1,1:0:-1]

array([[31],
       [25],
       [19],
       [13],
       [ 7],
       [ 1]])